[2025-03-20T00:00:38.533+0000] {processor.py:186} INFO - Started process (PID=22237) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:00:38.536+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:00:38.547+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:00:38.546+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:00:38.964+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:00:38.922+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:00:38.977+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:00:39.082+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.585 seconds
[2025-03-20T00:01:17.704+0000] {processor.py:186} INFO - Started process (PID=22302) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:01:17.709+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:01:17.718+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:01:17.718+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:01:17.758+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:01:17.750+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:01:17.760+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:01:17.830+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.146 seconds
[2025-03-20T00:01:56.723+0000] {processor.py:186} INFO - Started process (PID=22377) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:01:56.753+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:01:56.798+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:01:56.797+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:01:57.159+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:01:56.996+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:01:57.192+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:01:57.319+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.634 seconds
[2025-03-20T00:02:35.822+0000] {processor.py:186} INFO - Started process (PID=22431) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:02:35.833+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:02:35.835+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:02:35.834+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:02:35.871+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:02:35.864+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:02:35.873+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:02:35.945+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.137 seconds
[2025-03-20T00:03:06.034+0000] {processor.py:186} INFO - Started process (PID=22500) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:03:06.035+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:03:06.037+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:03:06.037+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:03:06.055+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:03:06.050+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:03:06.057+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:03:06.079+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.052 seconds
[2025-03-20T00:03:36.367+0000] {processor.py:186} INFO - Started process (PID=22568) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:03:36.368+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:03:36.370+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:03:36.370+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:03:36.436+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:03:36.430+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:03:36.438+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:03:36.470+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.114 seconds
[2025-03-20T00:04:08.920+0000] {processor.py:186} INFO - Started process (PID=22637) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:04:08.930+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:04:08.933+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:04:08.932+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:04:08.978+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:04:08.973+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:04:08.981+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:04:09.103+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.208 seconds
[2025-03-20T00:04:40.767+0000] {processor.py:186} INFO - Started process (PID=22706) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:04:40.768+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:04:40.770+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:04:40.770+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:04:40.792+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:04:40.787+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:04:40.794+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:04:40.852+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.096 seconds
[2025-03-20T00:05:12.654+0000] {processor.py:186} INFO - Started process (PID=22774) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:05:12.655+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:05:12.659+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:05:12.659+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:05:12.785+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:05:12.779+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:05:12.787+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:05:12.866+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.229 seconds
[2025-03-20T00:05:43.890+0000] {processor.py:186} INFO - Started process (PID=22842) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:05:43.891+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:05:43.894+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:05:43.893+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:05:43.924+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:05:43.912+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:05:43.926+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:05:43.972+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.095 seconds
[2025-03-20T00:06:14.830+0000] {processor.py:186} INFO - Started process (PID=22909) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:06:14.831+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:06:14.833+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:06:14.832+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:06:14.861+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:06:14.854+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:06:14.864+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:06:14.937+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.117 seconds
[2025-03-20T00:06:47.632+0000] {processor.py:186} INFO - Started process (PID=22978) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:06:47.638+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:06:47.649+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:06:47.649+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:06:47.769+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:06:47.762+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:06:47.771+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:06:47.918+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.320 seconds
[2025-03-20T00:07:20.075+0000] {processor.py:186} INFO - Started process (PID=23047) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:07:20.077+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:07:20.079+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:07:20.079+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:07:20.206+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:07:20.193+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:07:20.210+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:07:20.313+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.256 seconds
[2025-03-20T00:07:51.142+0000] {processor.py:186} INFO - Started process (PID=23116) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:07:51.143+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:07:51.146+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:07:51.145+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:07:51.165+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:07:51.160+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:07:51.167+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:07:51.221+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.092 seconds
[2025-03-20T00:08:23.237+0000] {processor.py:186} INFO - Started process (PID=23184) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:08:23.251+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:08:23.282+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:08:23.281+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:08:23.536+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:08:23.492+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:08:23.584+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:08:23.686+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.471 seconds
[2025-03-20T00:08:56.927+0000] {processor.py:186} INFO - Started process (PID=23259) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:08:56.928+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:08:56.940+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:08:56.938+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:08:57.258+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:08:57.224+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:08:57.265+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:08:57.317+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.412 seconds
[2025-03-20T00:09:32.358+0000] {processor.py:186} INFO - Started process (PID=23328) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:09:32.373+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:09:32.385+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:09:32.382+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:09:32.747+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:09:32.692+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:09:32.750+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:09:32.908+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.571 seconds
[2025-03-20T00:10:05.437+0000] {processor.py:186} INFO - Started process (PID=23397) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:10:05.442+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:10:05.455+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:10:05.453+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:10:05.507+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:10:05.495+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:10:05.510+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:10:05.596+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.198 seconds
[2025-03-20T00:10:35.958+0000] {processor.py:186} INFO - Started process (PID=23465) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:10:35.960+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:10:35.963+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:10:35.962+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:10:35.983+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:10:35.977+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:10:35.985+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:10:36.021+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.083 seconds
[2025-03-20T00:11:06.266+0000] {processor.py:186} INFO - Started process (PID=23533) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:11:06.268+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:11:06.271+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:11:06.270+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:11:06.299+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:11:06.294+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:11:06.301+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:11:06.343+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.088 seconds
[2025-03-20T00:11:39.292+0000] {processor.py:186} INFO - Started process (PID=23600) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:11:39.312+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:11:39.318+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:11:39.317+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:11:39.358+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:11:39.351+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:11:39.360+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:11:39.428+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.157 seconds
[2025-03-20T00:12:13.705+0000] {processor.py:186} INFO - Started process (PID=23667) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:12:13.707+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:12:13.711+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:12:13.710+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:12:13.797+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:12:13.782+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:12:13.800+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:12:13.896+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.214 seconds
[2025-03-20T00:12:44.810+0000] {processor.py:186} INFO - Started process (PID=23735) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:12:44.815+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:12:44.825+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:12:44.824+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:12:45.089+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:12:45.055+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:12:45.092+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:12:45.233+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.459 seconds
[2025-03-20T00:13:15.665+0000] {processor.py:186} INFO - Started process (PID=23803) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:13:15.667+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:13:15.671+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:13:15.669+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:13:15.700+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:13:15.693+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:13:15.704+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:13:15.779+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.125 seconds
[2025-03-20T00:13:52.292+0000] {processor.py:186} INFO - Started process (PID=23867) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:13:52.294+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:13:52.306+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:13:52.295+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:13:52.339+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:13:52.333+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:13:52.341+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:13:52.388+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.124 seconds
[2025-03-20T00:14:22.954+0000] {processor.py:186} INFO - Started process (PID=23935) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:14:22.956+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:14:22.958+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:14:22.958+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:14:22.989+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:14:22.983+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:14:22.992+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:14:23.035+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.098 seconds
[2025-03-20T00:14:57.618+0000] {processor.py:186} INFO - Started process (PID=24008) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:14:57.629+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:14:57.653+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:14:57.652+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:14:57.786+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:14:57.768+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:14:57.789+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:14:57.867+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.287 seconds
[2025-03-20T00:15:28.589+0000] {processor.py:186} INFO - Started process (PID=24073) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:15:28.605+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:15:28.626+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:15:28.622+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:15:28.843+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:15:28.837+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:15:28.864+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:15:29.219+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.743 seconds
[2025-03-20T00:16:29.653+0000] {processor.py:186} INFO - Started process (PID=24143) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:16:29.654+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:16:29.657+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:16:29.657+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:16:29.705+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:16:29.693+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:16:29.717+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:16:29.761+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.141 seconds
[2025-03-20T00:17:01.707+0000] {processor.py:186} INFO - Started process (PID=24203) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:17:01.711+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:17:01.714+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:17:01.713+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:17:02.055+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:17:02.020+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:17:02.131+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:17:02.232+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.554 seconds
[2025-03-20T00:17:36.605+0000] {processor.py:186} INFO - Started process (PID=24272) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:17:36.606+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:17:36.610+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:17:36.608+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:17:36.641+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:17:36.634+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:17:36.644+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:17:36.697+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.102 seconds
[2025-03-20T00:18:16.097+0000] {processor.py:186} INFO - Started process (PID=24340) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:18:16.110+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:18:16.127+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:18:16.127+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:18:16.173+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:18:16.159+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:18:16.176+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:18:16.291+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.231 seconds
[2025-03-20T00:18:51.683+0000] {processor.py:186} INFO - Started process (PID=24409) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:18:51.685+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:18:51.690+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:18:51.689+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:18:51.755+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:18:51.742+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:18:51.759+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:18:51.845+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.176 seconds
[2025-03-20T00:19:24.129+0000] {processor.py:186} INFO - Started process (PID=24482) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:19:24.130+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:19:24.135+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:19:24.132+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:19:24.248+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:19:24.233+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:19:24.251+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:19:24.420+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.303 seconds
[2025-03-20T00:19:56.563+0000] {processor.py:186} INFO - Started process (PID=24551) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:19:56.564+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:19:56.578+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:19:56.577+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:19:56.623+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:19:56.611+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:19:56.627+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:19:56.692+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.151 seconds
[2025-03-20T00:20:27.507+0000] {processor.py:186} INFO - Started process (PID=24617) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:20:27.517+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:20:27.520+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:20:27.519+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:20:27.573+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:20:27.555+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:20:27.593+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:20:27.760+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.260 seconds
[2025-03-20T00:20:59.029+0000] {processor.py:186} INFO - Started process (PID=24686) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:20:59.104+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:20:59.129+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:20:59.128+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:20:59.175+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:20:59.169+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:20:59.178+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:20:59.226+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.221 seconds
[2025-03-20T00:21:30.320+0000] {processor.py:186} INFO - Started process (PID=24740) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:21:30.337+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:21:30.347+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:21:30.346+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:21:30.530+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:21:30.470+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:21:30.535+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:21:30.684+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.374 seconds
[2025-03-20T00:22:02.037+0000] {processor.py:186} INFO - Started process (PID=24809) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:22:02.039+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:22:02.058+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:22:02.049+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:22:02.120+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:22:02.109+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:22:02.123+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:22:02.281+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.260 seconds
[2025-03-20T00:22:32.548+0000] {processor.py:186} INFO - Started process (PID=24879) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:22:32.550+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:22:32.552+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:22:32.551+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:22:32.575+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:22:32.569+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:22:32.577+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:22:32.726+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.189 seconds
[2025-03-20T00:23:03.322+0000] {processor.py:186} INFO - Started process (PID=24946) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:23:03.323+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:23:03.325+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:23:03.324+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:23:03.343+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:23:03.339+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:23:03.345+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:23:03.366+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.057 seconds
[2025-03-20T00:23:39.833+0000] {processor.py:186} INFO - Started process (PID=25007) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:23:39.841+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:23:39.846+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:23:39.845+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:23:40.751+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:23:40.497+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:23:40.894+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:23:40.969+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 1.163 seconds
[2025-03-20T00:24:11.084+0000] {processor.py:186} INFO - Started process (PID=25076) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:24:11.085+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:24:11.087+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:24:11.086+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:24:11.105+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:24:11.100+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:24:11.106+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:24:11.136+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.060 seconds
[2025-03-20T00:24:42.571+0000] {processor.py:186} INFO - Started process (PID=25144) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:24:42.583+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:24:42.593+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:24:42.593+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:24:42.741+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:24:42.733+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:24:42.743+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:24:42.816+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.268 seconds
[2025-03-20T00:25:13.898+0000] {processor.py:186} INFO - Started process (PID=25212) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:25:13.900+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:25:13.902+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:25:13.902+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:25:13.925+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:25:13.919+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:25:13.927+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:25:13.955+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.067 seconds
[2025-03-20T00:25:44.685+0000] {processor.py:186} INFO - Started process (PID=25278) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:25:44.686+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:25:44.688+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:25:44.688+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:25:44.710+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:25:44.705+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:25:44.712+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:25:44.749+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.073 seconds
[2025-03-20T00:26:15.015+0000] {processor.py:186} INFO - Started process (PID=25346) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:26:15.016+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:26:15.018+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:26:15.017+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:26:15.037+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:26:15.033+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:26:15.039+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:26:15.069+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.064 seconds
[2025-03-20T00:26:45.435+0000] {processor.py:186} INFO - Started process (PID=25415) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:26:45.436+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:26:45.438+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:26:45.437+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:26:45.458+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:26:45.453+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:26:45.461+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:26:45.492+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.065 seconds
[2025-03-20T00:27:16.003+0000] {processor.py:186} INFO - Started process (PID=25484) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:27:16.004+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:27:16.006+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:27:16.006+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:27:16.028+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:27:16.022+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:27:16.030+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:27:16.054+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.059 seconds
[2025-03-20T00:27:48.286+0000] {processor.py:186} INFO - Started process (PID=25552) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:27:48.303+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:27:48.309+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:27:48.309+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:27:48.401+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:27:48.360+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:27:48.417+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:27:48.643+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.389 seconds
[2025-03-20T00:28:19.245+0000] {processor.py:186} INFO - Started process (PID=25620) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:28:19.246+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:28:19.248+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:28:19.247+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:28:19.263+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:28:19.260+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:28:19.265+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:28:19.286+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.048 seconds
[2025-03-20T00:28:49.342+0000] {processor.py:186} INFO - Started process (PID=25690) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:28:49.343+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:28:49.345+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:28:49.344+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:28:49.365+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:28:49.360+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:28:49.370+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:28:49.408+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.077 seconds
[2025-03-20T00:29:19.948+0000] {processor.py:186} INFO - Started process (PID=25758) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:29:19.950+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:29:19.954+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:29:19.953+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:29:19.978+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:29:19.974+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:29:19.981+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:29:20.012+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.084 seconds
[2025-03-20T00:29:50.872+0000] {processor.py:186} INFO - Started process (PID=25834) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:29:50.879+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:29:50.883+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:29:50.882+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:29:50.918+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:29:50.911+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:29:50.920+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:29:50.962+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.108 seconds
[2025-03-20T00:30:21.105+0000] {processor.py:186} INFO - Started process (PID=25903) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:30:21.107+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:30:21.109+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:30:21.109+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:30:21.132+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:30:21.126+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:30:21.134+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:30:21.184+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.090 seconds
[2025-03-20T00:30:51.536+0000] {processor.py:186} INFO - Started process (PID=25970) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:30:51.538+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:30:51.547+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:30:51.547+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:30:51.609+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:30:51.602+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:30:51.613+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:30:51.675+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.160 seconds
[2025-03-20T00:31:21.951+0000] {processor.py:186} INFO - Started process (PID=26036) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:31:21.953+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:31:21.955+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:31:21.955+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:31:21.978+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:31:21.973+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:31:21.980+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:31:22.016+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.075 seconds
[2025-03-20T00:31:55.537+0000] {processor.py:186} INFO - Started process (PID=26102) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:31:55.539+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:31:55.540+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:31:55.540+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:31:55.578+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:31:55.573+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:31:55.583+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:31:55.620+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.093 seconds
[2025-03-20T00:32:26.382+0000] {processor.py:186} INFO - Started process (PID=26170) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:32:26.384+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:32:26.386+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:32:26.385+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:32:26.414+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:32:26.408+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:32:26.417+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:32:26.461+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.091 seconds
[2025-03-20T00:33:01.567+0000] {processor.py:186} INFO - Started process (PID=26233) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:33:01.568+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:33:01.571+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:33:01.570+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:33:01.596+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:33:01.590+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:33:01.599+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:33:01.659+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.105 seconds
[2025-03-20T00:33:32.390+0000] {processor.py:186} INFO - Started process (PID=26302) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:33:32.403+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:33:32.405+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:33:32.404+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:33:32.453+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:33:32.441+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:33:32.456+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:33:32.545+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.180 seconds
[2025-03-20T00:34:03.206+0000] {processor.py:186} INFO - Started process (PID=26372) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:34:03.210+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:34:03.215+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:34:03.214+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:34:03.250+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:34:03.243+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:34:03.256+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:34:03.319+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.129 seconds
[2025-03-20T00:34:34.019+0000] {processor.py:186} INFO - Started process (PID=26440) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:34:34.024+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:34:34.029+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:34:34.027+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:34:34.118+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:34:34.101+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:34:34.121+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:34:34.180+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.181 seconds
[2025-03-20T00:35:04.621+0000] {processor.py:186} INFO - Started process (PID=26509) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:35:04.623+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:35:04.625+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:35:04.624+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:35:04.645+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:35:04.640+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:35:04.647+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:35:04.681+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.071 seconds
[2025-03-20T00:35:35.221+0000] {processor.py:186} INFO - Started process (PID=26578) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:35:35.223+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:35:35.235+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:35:35.234+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:35:35.295+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:35:35.268+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:35:35.298+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:35:35.377+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.177 seconds
[2025-03-20T00:36:08.933+0000] {processor.py:186} INFO - Started process (PID=26631) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:36:08.937+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:36:08.947+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:36:08.947+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:36:09.040+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:36:09.012+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:36:09.051+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:36:09.134+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.222 seconds
[2025-03-20T00:36:39.844+0000] {processor.py:186} INFO - Started process (PID=26701) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:36:39.846+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:36:39.850+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:36:39.849+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:36:40.187+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:36:40.103+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:36:40.192+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:36:40.277+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.467 seconds
[2025-03-20T00:37:11.366+0000] {processor.py:186} INFO - Started process (PID=26770) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:37:11.368+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:37:11.371+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:37:11.370+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:37:11.411+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:37:11.403+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:37:11.414+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:37:11.275+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.124 seconds
[2025-03-20T00:37:41.539+0000] {processor.py:186} INFO - Started process (PID=26836) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:37:41.541+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:37:41.543+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:37:41.542+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:37:41.567+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:37:41.561+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:37:41.569+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:37:41.600+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.072 seconds
[2025-03-20T00:38:12.420+0000] {processor.py:186} INFO - Started process (PID=26904) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:38:12.422+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:38:12.424+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:38:12.424+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:38:12.580+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:38:12.558+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:38:12.586+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:38:12.763+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.359 seconds
[2025-03-20T00:38:43.465+0000] {processor.py:186} INFO - Started process (PID=26970) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:38:43.475+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:38:43.479+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:38:43.477+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:38:43.675+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:38:43.663+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:38:43.677+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:38:43.784+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.341 seconds
[2025-03-20T00:39:21.270+0000] {processor.py:186} INFO - Started process (PID=27045) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:39:21.278+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:39:21.294+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:39:21.293+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:39:21.638+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:39:21.629+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:39:21.640+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:39:21.703+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.457 seconds
[2025-03-20T00:39:52.412+0000] {processor.py:186} INFO - Started process (PID=27114) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:39:52.415+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:39:52.418+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:39:52.417+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:39:52.456+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:39:52.448+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:39:52.458+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:39:52.538+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.160 seconds
[2025-03-20T00:40:23.993+0000] {processor.py:186} INFO - Started process (PID=27170) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:40:23.995+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:40:23.998+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:40:23.998+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:40:24.030+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:40:24.024+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:40:24.036+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:40:24.092+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.131 seconds
[2025-03-20T00:40:54.647+0000] {processor.py:186} INFO - Started process (PID=27238) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:40:54.650+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:40:54.660+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:40:54.659+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:40:54.769+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:40:54.760+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:40:54.771+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:40:54.811+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.192 seconds
[2025-03-20T00:41:24.959+0000] {processor.py:186} INFO - Started process (PID=27308) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:41:24.961+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:41:24.962+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:41:24.962+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:41:24.992+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:41:24.982+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:41:24.994+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:41:25.068+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.119 seconds
[2025-03-20T00:41:55.766+0000] {processor.py:186} INFO - Started process (PID=27375) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:41:55.768+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:41:55.774+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:41:55.773+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:41:55.801+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:41:55.796+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:41:55.804+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:41:55.848+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.097 seconds
[2025-03-20T00:42:26.178+0000] {processor.py:186} INFO - Started process (PID=27445) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:42:26.179+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:42:26.182+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:42:26.181+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:42:26.203+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:42:26.198+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:42:26.205+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:42:26.239+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.072 seconds
[2025-03-20T00:43:00.534+0000] {processor.py:186} INFO - Started process (PID=27503) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:43:00.543+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:43:00.545+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:43:00.545+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:43:00.582+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:43:00.576+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:43:00.587+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:43:00.673+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.174 seconds
[2025-03-20T00:43:43.338+0000] {processor.py:186} INFO - Started process (PID=27572) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:43:43.349+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:43:43.352+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:43:43.351+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:43:43.446+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:43:43.433+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:43:43.455+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:43:43.512+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.192 seconds
[2025-03-20T00:44:14.953+0000] {processor.py:186} INFO - Started process (PID=27640) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:44:14.955+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:44:14.957+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:44:14.957+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:44:14.982+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:44:14.977+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:44:14.985+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:44:15.051+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.114 seconds
[2025-03-20T00:44:46.241+0000] {processor.py:186} INFO - Started process (PID=27708) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:44:46.243+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:44:46.245+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:44:46.245+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:44:46.296+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:44:46.282+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:44:46.307+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:44:46.355+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.127 seconds
[2025-03-20T00:45:16.554+0000] {processor.py:186} INFO - Started process (PID=27782) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:45:16.558+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:45:16.563+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:45:16.562+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:45:16.615+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:45:16.600+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:45:16.619+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:45:16.664+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 0.132 seconds
[2025-03-20T00:45:47.655+0000] {processor.py:186} INFO - Started process (PID=27851) to work on /opt/airflow/dags/test_dags.py
[2025-03-20T00:45:47.658+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dags.py for tasks to queue
[2025-03-20T00:45:47.662+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:45:47.662+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dags.py
[2025-03-20T00:45:48.903+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:45:48.308+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dags.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:45:48.949+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dags.py
[2025-03-20T00:45:49.025+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dags.py took 1.384 seconds
