[2025-03-20T00:00:37.654+0000] {processor.py:186} INFO - Started process (PID=22236) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:00:37.692+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:00:37.720+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:00:37.719+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:00:38.150+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:00:38.096+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:00:38.163+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:00:38.244+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.625 seconds
[2025-03-20T00:01:17.444+0000] {processor.py:186} INFO - Started process (PID=22301) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:01:17.448+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:01:17.450+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:01:17.449+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:01:17.711+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:01:17.616+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:01:17.718+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:01:17.808+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.396 seconds
[2025-03-20T00:01:56.249+0000] {processor.py:186} INFO - Started process (PID=22370) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:01:56.270+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:01:56.296+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:01:56.295+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:01:56.887+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:01:56.872+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:01:56.897+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:01:57.012+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.797 seconds
[2025-03-20T00:02:34.939+0000] {processor.py:186} INFO - Started process (PID=22430) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:02:34.973+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:02:35.034+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:02:35.033+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:02:35.529+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:02:35.376+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:02:35.531+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:02:35.687+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.789 seconds
[2025-03-20T00:03:05.807+0000] {processor.py:186} INFO - Started process (PID=22498) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:03:05.809+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:03:05.811+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:03:05.811+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:03:05.836+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:03:05.831+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:03:05.840+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:03:05.864+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.065 seconds
[2025-03-20T00:03:36.239+0000] {processor.py:186} INFO - Started process (PID=22567) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:03:36.240+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:03:36.242+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:03:36.241+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:03:36.260+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:03:36.257+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:03:36.262+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:03:36.291+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.064 seconds
[2025-03-20T00:04:08.890+0000] {processor.py:186} INFO - Started process (PID=22636) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:04:08.891+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:04:08.903+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:04:08.903+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:04:08.950+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:04:08.940+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:04:08.981+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:04:09.084+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.216 seconds
[2025-03-20T00:04:40.746+0000] {processor.py:186} INFO - Started process (PID=22705) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:04:40.750+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:04:40.752+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:04:40.752+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:04:40.775+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:04:40.770+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:04:40.777+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:04:40.843+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.114 seconds
[2025-03-20T00:05:12.448+0000] {processor.py:186} INFO - Started process (PID=22773) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:05:12.456+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:05:12.463+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:05:12.458+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:05:12.497+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:05:12.490+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:05:12.499+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:05:12.542+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.118 seconds
[2025-03-20T00:05:43.556+0000] {processor.py:186} INFO - Started process (PID=22841) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:05:43.557+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:05:43.561+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:05:43.559+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:05:43.591+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:05:43.585+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:05:43.593+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:05:43.648+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.105 seconds
[2025-03-20T00:06:14.618+0000] {processor.py:186} INFO - Started process (PID=22908) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:06:14.633+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:06:14.635+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:06:14.634+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:06:14.682+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:06:14.675+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:06:14.685+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:06:14.736+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.138 seconds
[2025-03-20T00:06:47.675+0000] {processor.py:186} INFO - Started process (PID=22977) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:06:47.704+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:06:47.739+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:06:47.738+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:06:47.805+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:06:47.787+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:06:48.037+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:06:48.118+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.464 seconds
[2025-03-20T00:07:20.075+0000] {processor.py:186} INFO - Started process (PID=23046) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:07:20.077+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:07:20.079+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:07:20.079+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:07:20.217+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:07:20.195+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:07:20.220+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:07:20.304+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.262 seconds
[2025-03-20T00:07:51.122+0000] {processor.py:186} INFO - Started process (PID=23115) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:07:51.126+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:07:51.129+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:07:51.129+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:07:51.147+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:07:51.143+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:07:51.149+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:07:51.185+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.075 seconds
[2025-03-20T00:08:23.184+0000] {processor.py:186} INFO - Started process (PID=23183) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:08:23.189+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:08:23.197+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:08:23.196+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:08:23.486+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:08:23.467+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:08:23.495+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:08:23.588+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.424 seconds
[2025-03-20T00:08:56.659+0000] {processor.py:186} INFO - Started process (PID=23258) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:08:56.661+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:08:56.680+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:08:56.676+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:08:56.709+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:08:56.704+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:08:56.712+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:08:56.777+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.149 seconds
[2025-03-20T00:09:27.310+0000] {processor.py:186} INFO - Started process (PID=23325) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:09:27.316+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:09:27.320+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:09:27.320+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:09:27.495+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:09:27.478+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:09:27.499+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:09:27.572+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.281 seconds
[2025-03-20T00:09:57.731+0000] {processor.py:186} INFO - Started process (PID=23394) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:09:57.818+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:09:57.869+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:09:57.868+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:09:57.931+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:09:57.926+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:09:57.933+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:09:57.962+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.252 seconds
[2025-03-20T00:10:28.101+0000] {processor.py:186} INFO - Started process (PID=23463) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:10:28.103+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:10:28.104+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:10:28.104+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:10:28.121+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:10:28.117+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:10:28.123+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:10:28.148+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.060 seconds
[2025-03-20T00:11:03.541+0000] {processor.py:186} INFO - Started process (PID=23531) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:11:03.565+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:11:03.576+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:11:03.575+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:11:03.648+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:11:03.632+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:11:03.653+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:11:03.729+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.198 seconds
[2025-03-20T00:11:35.952+0000] {processor.py:186} INFO - Started process (PID=23590) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:11:35.960+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:11:35.974+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:11:35.974+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:11:36.079+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:11:36.069+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:11:36.083+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:11:36.150+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.218 seconds
[2025-03-20T00:12:06.590+0000] {processor.py:186} INFO - Started process (PID=23658) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:12:06.592+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:12:06.620+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:12:06.619+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:12:06.711+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:12:06.698+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:12:06.714+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:12:06.814+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.257 seconds
[2025-03-20T00:12:37.933+0000] {processor.py:186} INFO - Started process (PID=23724) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:12:37.934+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:12:37.945+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:12:37.944+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:12:37.976+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:12:37.970+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:12:37.984+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:12:38.033+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.120 seconds
[2025-03-20T00:13:08.495+0000] {processor.py:186} INFO - Started process (PID=23792) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:13:08.496+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:13:08.498+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:13:08.497+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:13:08.514+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:13:08.510+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:13:08.516+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:13:08.538+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.051 seconds
[2025-03-20T00:13:43.652+0000] {processor.py:186} INFO - Started process (PID=23847) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:13:43.654+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:13:43.666+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:13:43.665+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:13:43.694+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:13:43.686+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:13:43.700+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:13:43.789+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.158 seconds
[2025-03-20T00:14:14.264+0000] {processor.py:186} INFO - Started process (PID=23916) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:14:14.276+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:14:14.280+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:14:14.279+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:14:14.407+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:14:14.376+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:14:14.410+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:14:14.490+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.243 seconds
[2025-03-20T00:14:44.987+0000] {processor.py:186} INFO - Started process (PID=23984) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:14:44.988+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:14:44.992+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:14:44.991+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:14:45.096+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:14:45.036+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:14:45.159+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:14:45.227+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.257 seconds
[2025-03-20T00:15:15.766+0000] {processor.py:186} INFO - Started process (PID=24053) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:15:15.776+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:15:15.780+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:15:15.779+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:15:15.863+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:15:15.850+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:15:15.879+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:15:15.985+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.240 seconds
[2025-03-20T00:15:56.099+0000] {processor.py:186} INFO - Started process (PID=24096) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:15:56.110+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:15:56.113+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:15:56.113+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:15:57.926+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:15:57.492+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:15:57.947+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:15:58.075+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 1.987 seconds
[2025-03-20T00:16:29.612+0000] {processor.py:186} INFO - Started process (PID=24142) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:16:29.625+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:16:29.629+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:16:29.629+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:16:29.685+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:16:29.674+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:16:29.689+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:16:29.758+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.168 seconds
[2025-03-20T00:17:01.681+0000] {processor.py:186} INFO - Started process (PID=24202) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:17:01.692+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:17:01.696+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:17:01.695+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:17:01.983+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:17:01.834+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:17:02.002+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:17:02.134+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.480 seconds
[2025-03-20T00:17:36.229+0000] {processor.py:186} INFO - Started process (PID=24271) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:17:36.236+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:17:36.242+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:17:36.242+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:17:36.275+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:17:36.265+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:17:36.277+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:17:36.357+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.141 seconds
[2025-03-20T00:18:15.653+0000] {processor.py:186} INFO - Started process (PID=24339) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:18:15.655+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:18:15.667+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:18:15.667+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:18:15.709+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:18:15.702+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:18:15.717+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:18:15.822+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.195 seconds
[2025-03-20T00:18:51.264+0000] {processor.py:186} INFO - Started process (PID=24408) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:18:51.275+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:18:51.278+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:18:51.278+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:18:51.351+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:18:51.332+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:18:51.354+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:18:51.457+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.335 seconds
[2025-03-20T00:19:23.964+0000] {processor.py:186} INFO - Started process (PID=24481) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:19:23.967+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:19:23.969+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:19:23.968+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:19:23.992+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:19:23.987+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:19:23.997+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:19:24.029+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.078 seconds
[2025-03-20T00:19:54.307+0000] {processor.py:186} INFO - Started process (PID=24548) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:19:54.312+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:19:54.315+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:19:54.314+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:19:54.363+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:19:54.349+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:19:54.365+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:19:54.428+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.155 seconds
[2025-03-20T00:20:27.272+0000] {processor.py:186} INFO - Started process (PID=24616) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:20:27.274+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:20:27.276+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:20:27.275+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:20:27.316+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:20:27.305+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:20:27.319+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:20:27.355+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.092 seconds
[2025-03-20T00:20:57.919+0000] {processor.py:186} INFO - Started process (PID=24679) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:20:57.921+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:20:57.924+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:20:57.924+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:20:57.952+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:20:57.947+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:20:57.957+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:20:58.007+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.114 seconds
[2025-03-20T00:21:30.288+0000] {processor.py:186} INFO - Started process (PID=24739) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:21:30.290+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:21:30.293+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:21:30.292+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:21:30.467+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:21:30.395+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:21:30.473+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:21:30.539+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.283 seconds
[2025-03-20T00:22:01.609+0000] {processor.py:186} INFO - Started process (PID=24808) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:22:01.612+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:22:01.615+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:22:01.615+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:22:01.691+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:22:01.668+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:22:01.707+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:22:01.777+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.181 seconds
[2025-03-20T00:22:32.160+0000] {processor.py:186} INFO - Started process (PID=24878) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:22:32.162+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:22:32.164+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:22:32.163+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:22:32.236+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:22:32.218+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:22:32.261+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:22:32.411+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.263 seconds
[2025-03-20T00:23:03.302+0000] {processor.py:186} INFO - Started process (PID=24945) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:23:03.305+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:23:03.307+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:23:03.307+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:23:03.329+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:23:03.325+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:23:03.331+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:23:03.357+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.066 seconds
[2025-03-20T00:23:39.181+0000] {processor.py:186} INFO - Started process (PID=25006) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:23:39.185+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:23:39.198+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:23:39.197+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:23:39.275+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:23:39.267+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:23:39.279+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:23:39.353+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.182 seconds
[2025-03-20T00:24:09.839+0000] {processor.py:186} INFO - Started process (PID=25074) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:24:09.840+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:24:09.843+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:24:09.843+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:24:09.863+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:24:09.859+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:24:09.865+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:24:09.895+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.066 seconds
[2025-03-20T00:24:41.139+0000] {processor.py:186} INFO - Started process (PID=25138) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:24:41.140+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:24:41.142+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:24:41.142+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:24:41.317+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:24:41.242+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:24:41.337+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:24:41.396+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.288 seconds
[2025-03-20T00:25:11.544+0000] {processor.py:186} INFO - Started process (PID=25206) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:25:11.545+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:25:11.548+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:25:11.547+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:25:11.570+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:25:11.564+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:25:11.572+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:25:11.606+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.074 seconds
[2025-03-20T00:25:42.027+0000] {processor.py:186} INFO - Started process (PID=25274) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:25:42.034+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:25:42.050+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:25:42.049+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:25:42.188+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:25:42.136+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:25:42.204+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:25:42.349+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.353 seconds
[2025-03-20T00:26:12.611+0000] {processor.py:186} INFO - Started process (PID=25343) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:26:12.616+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:26:12.621+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:26:12.619+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:26:12.649+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:26:12.643+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:26:12.651+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:26:12.701+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.106 seconds
[2025-03-20T00:26:42.795+0000] {processor.py:186} INFO - Started process (PID=25410) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:26:42.797+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:26:42.800+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:26:42.799+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:26:42.821+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:26:42.816+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:26:42.823+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:26:42.851+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.069 seconds
[2025-03-20T00:27:13.318+0000] {processor.py:186} INFO - Started process (PID=25479) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:27:13.321+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:27:13.324+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:27:13.323+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:27:13.376+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:27:13.368+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:27:13.379+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:27:13.460+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.156 seconds
[2025-03-20T00:27:44.047+0000] {processor.py:186} INFO - Started process (PID=25544) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:27:44.053+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:27:44.058+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:27:44.057+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:27:44.107+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:27:44.095+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:27:44.111+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:27:44.227+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.205 seconds
[2025-03-20T00:28:14.741+0000] {processor.py:186} INFO - Started process (PID=25612) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:28:14.742+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:28:14.746+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:28:14.746+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:28:14.767+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:28:14.761+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:28:14.769+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:28:14.808+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.079 seconds
[2025-03-20T00:28:45.446+0000] {processor.py:186} INFO - Started process (PID=25682) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:28:45.451+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:28:45.462+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:28:45.461+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:28:45.509+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:28:45.503+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:28:45.511+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:28:45.554+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.129 seconds
[2025-03-20T00:29:15.699+0000] {processor.py:186} INFO - Started process (PID=25751) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:29:15.701+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:29:15.703+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:29:15.702+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:29:15.726+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:29:15.718+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:29:15.729+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:29:15.770+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.083 seconds
[2025-03-20T00:29:46.604+0000] {processor.py:186} INFO - Started process (PID=25821) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:29:46.608+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:29:46.612+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:29:46.611+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:29:46.665+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:29:46.657+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:29:46.670+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:29:46.715+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.130 seconds
[2025-03-20T00:30:18.973+0000] {processor.py:186} INFO - Started process (PID=25890) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:30:18.982+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:30:18.990+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:30:18.985+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:30:19.134+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:30:19.105+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:30:19.156+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:30:19.312+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.378 seconds
[2025-03-20T00:30:49.967+0000] {processor.py:186} INFO - Started process (PID=25964) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:30:49.969+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:30:49.972+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:30:49.971+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:30:50.012+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:30:50.003+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:30:50.016+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:30:50.119+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.171 seconds
[2025-03-20T00:31:20.589+0000] {processor.py:186} INFO - Started process (PID=26033) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:31:20.590+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:31:20.593+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:31:20.592+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:31:20.613+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:31:20.609+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:31:20.615+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:31:20.653+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.075 seconds
[2025-03-20T00:31:55.388+0000] {processor.py:186} INFO - Started process (PID=26101) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:31:55.390+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:31:55.392+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:31:55.391+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:31:55.422+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:31:55.416+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:31:55.424+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:31:55.466+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.096 seconds
[2025-03-20T00:32:26.207+0000] {processor.py:186} INFO - Started process (PID=26169) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:32:26.209+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:32:26.222+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:32:26.221+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:32:26.255+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:32:26.250+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:32:26.257+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:32:26.353+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.172 seconds
[2025-03-20T00:33:00.766+0000] {processor.py:186} INFO - Started process (PID=26232) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:33:00.797+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:33:00.831+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:33:00.831+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:33:01.282+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:33:01.258+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:33:01.285+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:33:01.394+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.906 seconds
[2025-03-20T00:33:32.409+0000] {processor.py:186} INFO - Started process (PID=26301) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:33:32.414+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:33:32.418+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:33:32.416+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:33:32.547+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:33:32.468+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:33:32.553+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:33:32.647+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.277 seconds
[2025-03-20T00:34:03.162+0000] {processor.py:186} INFO - Started process (PID=26371) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:34:03.166+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:34:03.172+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:34:03.171+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:34:03.237+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:34:03.230+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:34:03.240+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:34:03.316+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.193 seconds
[2025-03-20T00:34:33.964+0000] {processor.py:186} INFO - Started process (PID=26439) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:34:33.966+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:34:33.968+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:34:33.968+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:34:34.062+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:34:34.030+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:34:34.071+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:34:34.131+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.190 seconds
[2025-03-20T00:35:04.608+0000] {processor.py:186} INFO - Started process (PID=26508) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:35:04.609+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:35:04.611+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:35:04.611+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:35:04.635+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:35:04.629+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:35:04.637+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:35:04.669+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.075 seconds
[2025-03-20T00:35:35.191+0000] {processor.py:186} INFO - Started process (PID=26577) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:35:35.193+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:35:35.197+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:35:35.196+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:35:35.298+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:35:35.282+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:35:35.311+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:35:35.379+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.212 seconds
[2025-03-20T00:36:07.847+0000] {processor.py:186} INFO - Started process (PID=26630) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:36:07.857+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:36:07.867+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:36:07.866+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:36:07.938+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:36:07.908+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:36:08.063+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:36:08.251+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.426 seconds
[2025-03-20T00:36:38.475+0000] {processor.py:186} INFO - Started process (PID=26696) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:36:38.481+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:36:38.484+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:36:38.483+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:36:38.516+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:36:38.509+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:36:38.518+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:36:38.561+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.097 seconds
[2025-03-20T00:37:09.397+0000] {processor.py:186} INFO - Started process (PID=26764) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:37:09.413+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:37:09.421+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:37:09.421+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:37:09.449+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:37:09.442+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:37:09.451+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:37:09.549+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.181 seconds
[2025-03-20T00:37:39.825+0000] {processor.py:186} INFO - Started process (PID=26832) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:37:39.827+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:37:39.829+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:37:39.829+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:37:39.853+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:37:39.848+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:37:39.855+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:37:39.888+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.074 seconds
[2025-03-20T00:38:10.841+0000] {processor.py:186} INFO - Started process (PID=26900) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:38:10.854+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:38:10.865+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:38:10.864+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:38:10.934+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:38:10.918+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:38:10.938+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:38:11.342+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.524 seconds
[2025-03-20T00:38:43.432+0000] {processor.py:186} INFO - Started process (PID=26969) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:38:43.437+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:38:43.446+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:38:43.446+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:38:43.645+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:38:43.534+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:38:43.652+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:38:43.753+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.343 seconds
[2025-03-20T00:39:20.332+0000] {processor.py:186} INFO - Started process (PID=27044) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:39:20.355+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:39:20.373+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:39:20.372+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:39:20.896+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:39:20.857+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:39:20.906+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:39:21.173+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.864 seconds
[2025-03-20T00:39:52.181+0000] {processor.py:186} INFO - Started process (PID=27113) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:39:52.182+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:39:52.184+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:39:52.184+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:39:52.225+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:39:52.217+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:39:52.227+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:39:52.284+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.115 seconds
[2025-03-20T00:40:23.476+0000] {processor.py:186} INFO - Started process (PID=27169) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:40:23.478+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:40:23.491+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:40:23.481+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:40:23.535+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:40:23.528+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:40:23.538+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:40:23.618+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.175 seconds
[2025-03-20T00:40:54.313+0000] {processor.py:186} INFO - Started process (PID=27236) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:40:54.315+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:40:54.318+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:40:54.317+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:40:54.355+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:40:54.349+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:40:54.357+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:40:54.389+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.108 seconds
[2025-03-20T00:41:24.532+0000] {processor.py:186} INFO - Started process (PID=27305) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:41:24.534+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:41:24.537+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:41:24.536+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:41:24.568+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:41:24.557+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:41:24.570+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:41:24.629+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.112 seconds
[2025-03-20T00:41:55.739+0000] {processor.py:186} INFO - Started process (PID=27374) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:41:55.740+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:41:55.743+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:41:55.743+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:41:55.781+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:41:55.772+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:41:55.784+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:41:55.820+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.106 seconds
[2025-03-20T00:42:25.947+0000] {processor.py:186} INFO - Started process (PID=27444) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:42:25.949+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:42:25.952+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:42:25.952+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:42:25.987+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:42:25.977+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:42:25.989+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:42:26.074+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.139 seconds
[2025-03-20T00:42:59.794+0000] {processor.py:186} INFO - Started process (PID=27502) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:42:59.796+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:42:59.801+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:42:59.801+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:43:00.109+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:43:00.011+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:43:00.111+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:43:00.192+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.432 seconds
[2025-03-20T00:43:42.851+0000] {processor.py:186} INFO - Started process (PID=27571) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:43:42.868+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:43:42.886+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:43:42.885+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:43:43.081+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:43:43.028+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:43:43.127+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:43:43.237+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.436 seconds
[2025-03-20T00:44:14.900+0000] {processor.py:186} INFO - Started process (PID=27639) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:44:14.903+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:44:14.930+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:44:14.929+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:44:14.966+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:44:14.960+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:44:14.968+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:44:15.015+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.129 seconds
[2025-03-20T00:44:45.823+0000] {processor.py:186} INFO - Started process (PID=27707) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:44:45.824+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:44:45.828+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:44:45.827+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:44:45.866+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:44:45.861+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:44:45.882+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:44:45.921+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.110 seconds
[2025-03-20T00:45:16.308+0000] {processor.py:186} INFO - Started process (PID=27781) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:45:16.320+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:45:16.324+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:45:16.323+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:45:16.359+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:45:16.351+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:45:16.361+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:45:16.394+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.104 seconds
[2025-03-20T00:45:47.090+0000] {processor.py:186} INFO - Started process (PID=27849) to work on /opt/airflow/dags/testfinal.py
[2025-03-20T00:45:47.096+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/testfinal.py for tasks to queue
[2025-03-20T00:45:47.108+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:45:47.107+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/testfinal.py
[2025-03-20T00:45:47.320+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:45:47.275+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/testfinal.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/testfinal.py", line 4, in <module>
    from airflow.providers.dbt.cloud.operators.dbt import DbtRunOperator
ModuleNotFoundError: No module named 'airflow.providers.dbt'
[2025-03-20T00:45:47.348+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/testfinal.py
[2025-03-20T00:45:47.453+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/testfinal.py took 0.396 seconds
